stages:
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - src/data/data_preprocessing.py
    - data/raw/train.csv
    - data/raw/test.csv
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  feature_engg:
    cmd: python src/features/feature_engg.py
    deps:
    - src/features/feature_engg.py
    - data/processed/train.csv
    - data/processed/test.csv
    outs:
    - data/interim/train_bow.csv
    - data/interim/test_bow.csv

  modelling:
    cmd: python src/models/modeling.py
    deps:
    - src/models/modeling.py
    - data/interim/train_bow.csv
    outs:
    - models/random_forest_model.pkl

  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - src/models/model_evaluation.py
    - models/random_forest_model.pkl
    - data/interim/test_bow.csv
    outs:
    - reports/model_evaluation.json
